name: Generate

on:
  pull_request:
    branches: [ master ]

env:
  DOTNET_VERSION: 3.1.x

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Remove old codes
      run: |
        mv src/Freee.Accounting/Client/ApiClient.Version.cs src/Freee.Accounting/ApiClient.Version.cs
        rm -rf src/Freee.Accounting/Api src/Freee.Accounting/Client src/Freee.Accounting/Models

    - name: Generate APIs
      run: |
        docker run --rm -u "$(id -u $USER):$(id -g $USER)" -v "${PWD}:/local" openapitools/openapi-generator-cli:latest-release generate \
        -i "https://dev.azure.com/freee-developer/accounting-sdk/_apis/git/repositories/freee-api-schema-v3/items?path=%2Fv2020_06_15%2Fopen-api-3%2Fapi-schema.yml&download=false&api-version=6.0-preview.1" \
        -c /local/.openapi-generator/config.yml \
        -g csharp-netcore \
        -o /local/

    - name: Add API Versioning
      run: |
        mv src/Freee.Accounting/ApiClient.Version.cs src/Freee.Accounting/Client/ApiClient.Version.cs

    - name: Git
      run: |
        git add *.cs
        git commit -m "Generated by TAG_NAME"
        git reset --hard HEAD
        git clean -fdx

    - name: Use .NET Core ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build projects
      run: dotnet build -c Release

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
